global:
  externalUrl: "http://localhost:30464"
  hosts:
    domain: localhost
  ingress:
    enabled: false
  minio:
    enabled: true
  appConfig:
    artifacts:
      bucket: gitlab-artifacts
      connection:
        secret: gitlab-minio-secret
        key: connection
    lfs:
      bucket: gitlab-lfs
      connection:
        secret: gitlab-minio-secret
        key: connection
    uploads:
      bucket: gitlab-uploads
      connection:
        secret: gitlab-minio-secret
        key: connection
    packages:
      bucket: gitlab-packages
      connection:
        secret: gitlab-minio-secret
        key: connection
    backups:
      bucket: gitlab-backups
      tmpBucket: gitlab-tmp

gitlab:
  webservice:
    service:
      type: NodePort
      nodePort: 30464
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi
  gitaly:
    persistence:
      enabled: false

gitlab-runner:
  install: false

certmanager:
  install: false

certmanager-issuer:
  email: "dev@localhost.local"

prometheus:
  install: false

postgresql:
  install: true
  postgresqlUsername: gitlab
  postgresqlPassword: gitlab
  postgresqlDatabase: gitlabhq_production
  persistence:
    enabled: false

toolbox:
  backups:
    objectStorage:
      config:
        secret: gitlab-minio-secret
        key: connection
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi

minio:
  persistence:
    enabled: false

sidekiq:
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1Gi
