apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: IoT
spec:
  destination:
    name: in-cluster
    namespace: dev
  source:
    path: /manifest
    repoURL: https://github.com/TFHD/Inception-of-Things-ressources
    targetRevision: HEAD
  sources: []
  project: IoT
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
