Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  #============================FIRST VM==============================
  config.vm.define "sabarthoS" do |control|
    control.vm.hostname = "sabarthoS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sabarthoS"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/provisionS.sh"
  end
  #===========================SECOND VM==============================
  config.vm.define "sabarthoSW" do |control|
    control.vm.hostname = "sabarthoSW"
    control.vm.network "private_network", ip: "192.168.56.111"

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sabarthoSW"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/provisionSW.sh"
  end
end
